[package]
name = "slas"
version = "0.1.1"
edition = "2018"
authors = ["Aksel Mannstaedt <unic0rn9k@protonmail.com>"]
license = "Apache-2.0"

repository = "https://github.com/unic0rn9k/slas"
description = "Static Linear Algebra System"

keywords = ["matrix", "blas", "linearalgebra", "matrix", "vectors"]
categories = ["data-structures", "science", "mathematics"]

readme = "README.md"

[dependencies]
blas-src = { version = "0.8.0", features = ["blis"] }
cblas-sys = "0.1.4"
num = "0.4.0"

[workspace]
members = ["tests"]
