[package]
name = "slas"
version = "0.1.0"
edition = "2018"

[dependencies]
blas-src = { version = "0.8.0", features = ["blis"] }
cblas-sys = "0.1.4"
num = "0.4.0"

[workspace]
members = ["tests"]

[profile.release]
lto = true
opt-level = 3
